name: Generate Docker Image
on:
  push:
    tags:
      - '*'
env:
  IMAGE_VERSION: ${{ github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Use Node 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.API_URL }}" >> .env
      - name: Install dependencies
        run: npm i --force
      - name: Build
        run: npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: daniel101/norte4j-web:${{ env.IMAGE_VERSION }},daniel101/norte4j-web:latest
